<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calendar-day_31Calgary</name>
   <tag></tag>
   <elementGuidId>9c5759c9-8d6c-434d-9b2e-0ca288c84eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flt-modaldialog']/div/two-month-calendar/div/div/calendar-month[2]/calendar-week[5]/calendar-day[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>calendar-day</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jstcache</name>
      <type>Main</type>
      <value>9752</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-day</name>
      <type>Main</type>
      <value>2019-07-31</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>fire.cal_select_day;mouseenter:fire.cal_enter_day;mouseleave:fire.cal_leave_day</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsinstance</name>
      <type>Main</type>
      <value>*3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gws-travel-calendar__day gws-travel-calendar__active gws-travel-calendar__selected-day gws-travel-calendar__selected-range gws-travel-calendar__last</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsan</name>
      <type>Main</type>
      <value>t-bB_lIPWO_Uo,7.gws-travel-calendar__day,7.gws-travel-calendar__active,7.gws-travel-calendar__selected-day,7.gws-travel-calendar__selected-range,7.gws-travel-calendar__last,0.data-day,0.data-last,0.role,22.jsaction</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-last</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31Calgary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-modaldialog&quot;)/div[1]/two-month-calendar[@class=&quot;qcXwoe gws-travel-calendar__two-month-calendar gws-travel-calendar__clean&quot;]/div[@class=&quot;gws-travel-calendar__scroll-container&quot;]/div[@class=&quot;gws-travel-calendar__calendar&quot;]/calendar-month[@class=&quot;gws-travel-calendar__month gws-travel-calendar__show-annotations&quot;]/calendar-week[@class=&quot;gws-travel-calendar__week&quot;]/calendar-day[@class=&quot;gws-travel-calendar__day gws-travel-calendar__active gws-travel-calendar__selected-day gws-travel-calendar__selected-range gws-travel-calendar__last&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flt-modaldialog']/div/two-month-calendar/div/div/calendar-month[2]/calendar-week[5]/calendar-day[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calgary'])[8]/following::calendar-day[18]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calgary'])[7]/following::calendar-day[29]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='August'])[1]/preceding::calendar-day[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//calendar-month[2]/calendar-week[5]/calendar-day[4]</value>
   </webElementXpaths>
</WebElementEntity>
