<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu-item_Business (1)</name>
   <tag></tag>
   <elementGuidId>30fecdca-a544-431e-a8c2-70dd775edc62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flt-app']/div[2]/main/div[3]/div/div[3]/div/div/div[3]/div/div[2]/div/menu-item[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>menu-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsinstance</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>X4hwq flt-subhead2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitemradio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsl</name>
      <type>Main</type>
      <value>$x 4;$t t-wKO3kv0zAXM;$x 0;$t t-wSoPp6_m_tk;$x 0;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-seatingclass</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flt-ve</name>
      <type>Main</type>
      <value>cabin_option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>cOsqkb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsvs</name>
      <type>Main</type>
      <value>'cOsqkb';</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jssc</name>
      <type>Main</type>
      <value>t-wSoPp6_m_tk:fQt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tab-index</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-app&quot;)/div[@class=&quot;gws-flights__flex-column gws-flights__flex-grow&quot;]/main[@class=&quot;gws-flights__flex-column gws-flights__active-tab gws-flights__home-page&quot;]/div[@class=&quot;gws-flights__center-content gws-flights__scrollbar-padding&quot;]/div[@class=&quot;gws-flights__homepage-form gws-flights-form__search-form gws-flights-form__homepage&quot;]/div[@class=&quot;gws-flights-form__form-card&quot;]/div[@class=&quot;gws-flights-form__form-content&quot;]/div[@class=&quot;gws-flights-form__secondary-constraints gws-flights__flex-box&quot;]/div[@class=&quot;gws-flights__seating_class_dropdown&quot;]/div[@class=&quot;t5Hjm&quot;]/div[@class=&quot;z6mTee Zzj1ye cKItof&quot;]/div[1]/menu-item[@class=&quot;X4hwq flt-subhead2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flt-app']/div[2]/main/div[3]/div/div[3]/div/div/div[3]/div/div[2]/div/menu-item[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium Economy'])[2]/following::menu-item[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Economy'])[2]/following::menu-item[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Class'])[2]/preceding::menu-item[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/menu-item[3]</value>
   </webElementXpaths>
</WebElementEntity>
