<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Multi-city</name>
   <tag></tag>
   <elementGuidId>4b84dc43-4731-4394-a3f7-470977858e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flt-app']/div[2]/main/div[3]/div/div[3]/div/div/div/dropdown-menu/div/div[2]/menu-item[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jstcache</name>
      <type>Main</type>
      <value>689</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Multi-city</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flt-app&quot;)/div[@class=&quot;gws-flights__flex-column gws-flights__flex-grow&quot;]/main[@class=&quot;gws-flights__flex-column gws-flights__active-tab gws-flights__home-page&quot;]/div[@class=&quot;gws-flights__center-content gws-flights__scrollbar-padding&quot;]/div[@class=&quot;gws-flights__homepage-form gws-flights-form__search-form gws-flights-form__homepage&quot;]/div[@class=&quot;gws-flights-form__form-card&quot;]/div[@class=&quot;gws-flights-form__form-content&quot;]/div[@class=&quot;gws-flights-form__secondary-constraints gws-flights__flex-box&quot;]/div[1]/dropdown-menu[1]/div[@class=&quot;mSPnZKpnf91__container&quot;]/div[@class=&quot;mSPnZKpnf91__menu mSPnZKpnf91__cover-button mSPnZKpnf91__open&quot;]/menu-item[@class=&quot;mSPnZKpnf91__menu-item flt-subhead2&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flt-app']/div[2]/main/div[3]/div/div[3]/div/div/div/dropdown-menu/div/div[2]/menu-item[3]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-way'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round trip'])[2]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Economy'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Economy'])[2]/preceding::span[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//menu-item[3]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/preceding::span[5]</value>
   </webElementXpaths>
</WebElementEntity>
